// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package echo

import (
	"cloud.google.com/go/firestore"
	"firebase.google.com/go/auth"
	"firebase.google.com/go/storage"
	converter2 "github.com/pt-suzuki/auto_transcription/src/controllers/echo/converter"
	"github.com/pt-suzuki/auto_transcription/src/domains/convert_result"
	"github.com/pt-suzuki/auto_transcription/src/domains/converter"
	"github.com/pt-suzuki/auto_transcription/src/domains/uploader"
	"github.com/pt-suzuki/auto_transcription/src/handler"
	"github.com/pt-suzuki/auto_transcription/src/middleware"
	converter3 "github.com/pt-suzuki/auto_transcription/src/middleware/converter"
)

// Injectors from wire.go:

func Wire(fireStoreClient *firestore.Client, fireStorageClient *storage.Client, firebaseAuthClient *auth.Client) *Provider {
	translator := convert_result.NewConvertResultTranslator()
	repository := convert_result.NewRepository(fireStoreClient, translator)
	useCase := convert_result.NewUseCase(repository)
	responseHandler := handler.NewResponseHandler()
	speechToTextTranslator := converter.NewSpeechToTextTranslator(responseHandler)
	uploaderTranslator := uploader.NewTranslator()
	uploaderRepository := uploader.NewRepository(fireStoreClient, fireStorageClient, uploaderTranslator)
	uploaderUseCase := uploader.NewUseCase(uploaderRepository, useCase)
	speechToTextRepository := converter.NewSpeechToTextRepository(speechToTextTranslator)
	speechToTextUseCase := converter.NewSpeechToTextUseCase(useCase, speechToTextTranslator, uploaderUseCase, speechToTextRepository)
	convertSpeechToTextResponder := converter2.NewConvertSpeechToTextResponder()
	convertSpeechToTextAction := converter2.NewConvertSpeechToTextAction(speechToTextUseCase, speechToTextTranslator, convertSpeechToTextResponder)
	firebaseTokenVerifiedMiddleware := middleware.NewFirebaseTokenVerifiedMiddleware(firebaseAuthClient)
	convertSpeechToTextValidatorMiddleware := converter3.NewConvertSpeechToTextValidatorMiddleware(speechToTextTranslator)
	converterMiddlewareProvider := NewConverterMiddlewareProvider(convertSpeechToTextValidatorMiddleware)
	middlewareProvider := NewMiddlewareProvider(firebaseTokenVerifiedMiddleware, converterMiddlewareProvider)
	provider := NewProvider(convertSpeechToTextAction, middlewareProvider)
	return provider
}
