// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package echo

import (
	"cloud.google.com/go/firestore"
	"firebase.google.com/go/auth"
	"firebase.google.com/go/storage"
	converter2 "github.com/pt-suzuki/auto_transcription/src/controllers/echo/converter"
	"github.com/pt-suzuki/auto_transcription/src/domains/converter"
	"github.com/pt-suzuki/auto_transcription/src/domains/uploader"
	"github.com/pt-suzuki/auto_transcription/src/handler"
	"github.com/pt-suzuki/auto_transcription/src/middleware"
)

// Injectors from wire.go:

func Wire(fireStoreClient *firestore.Client, fireStorageClient *storage.Client, firebaseAuthClient *auth.Client) *Provider {
	convertResultTranslator := converter.NewConvertResultTranslator()
	convertResultRepository := converter.NewConvertResultRepository(fireStoreClient, convertResultTranslator)
	convertResultUseCase := converter.NewConvertResultUseCase(convertResultRepository)
	responseHandler := handler.NewResponseHandler()
	speechToTextTranslator := converter.NewSpeechToTextTranslator(responseHandler)
	translator := uploader.NewTranslator()
	repository := uploader.NewRepository(fireStorageClient, translator)
	useCase := uploader.NewUseCase(repository)
	speechToTextRepository := converter.NewSpeechToTextRepository(speechToTextTranslator)
	speechToTextUseCase := converter.NewSpeechToTextUseCase(convertResultUseCase, speechToTextTranslator, useCase, speechToTextRepository)
	convertSpeechToTextResponder := converter2.NewConvertSpeechToTextResponder()
	convertSpeechToTextAction := converter2.NewConvertSpeechToTextAction(speechToTextUseCase, speechToTextTranslator, convertSpeechToTextResponder)
	firebaseTokenVerifiedMiddleware := middleware.NewFirebaseTokenVerifiedMiddleware(firebaseAuthClient)
	provider := NewProvider(convertSpeechToTextAction, firebaseTokenVerifiedMiddleware)
	return provider
}
